### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by justpeanuts** [BrayanDSO/Markdown_to_Anki#20]
*Please replace the space inside the brackets with an **x** if the following items apply:*
- [x] I've checked if anyone else reported this problem before by looking through the issue reports

**Info**:
- OS: linux
- Python version: 3.8.1
- Anki version: 2.1.35 (84dcaa86)

**Describe the bug**
I get this error when running $ python3 Markdown_to_Anki.py 
```
Traceback (most recent call last):
  File "Markdown_to_Anki.py", line 18, in <module>
    import anki
  File "/home/arjun/.local/lib/python3.8/site-packages/anki/__init__.py", line 7, in <module>
    from anki.collection import Collection
  File "/home/arjun/.local/lib/python3.8/site-packages/anki/collection.py", line 16, in <module>
    import anki._backend.backend_pb2 as _pb
  File "/home/arjun/.local/lib/python3.8/site-packages/anki/_backend/__init__.py", line 10, in <module>
    from anki._backend.generated import RustBackendGenerated
  File "/home/arjun/.local/lib/python3.8/site-packages/anki/_backend/generated.py", line 18, in <module>
    import anki._backend.backend_pb2 as pb
  File "/home/arjun/.local/lib/python3.8/site-packages/anki/_backend/backend_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.
```
I already ran install-requirements.py

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log information**
*Please open your Markdown_to_Anki folder, open "log.txt", copy and paste the result between the backticks below:*
```

```

**Comment by BrayanDSO** [comment]
This seems like a problem with anki library version.

Based on your issue, I tested the script with every python version since 3.8. 

Even with anki specifying on its code that it works with python 3.7+ and its docs python 3.8+, its library only is installable with python 3.8.4 (at the version Markdown_to_Anki uses). 
So I updated the requirements to _3.8.4+_ and made some checks at 0.9 version. On my linux build it is working just nice.

Please, test the new version I just shipped [here](https://github.com/BrayanDSO/Markdown_to_Anki/releases/tag/v0.9). It has a linux executable, so you don't need to change your python version. 

Since the executable is still experimental, if it doesn't works for you, install a newer python version and download the new [M2A_py](https://github.com/BrayanDSO/Markdown_to_Anki/releases/download/v0.9/M2A_py.zip), then run `install_requirements.py` again.

Let me know if this fixes your problem or any issues appear

**Comment by BrayanDSO** [comment]
p.s. Linux executable is for 64 bits
